logging:
  level: INFO
  loggers:
    holidays: DEBUG

# Database settings.
database:
    # the name of the JDBC driver, mysql in our case
    driverClass: com.mysql.jdbc.Driver
    # the username
    user: Gregor
    # the password
    password: tralala13
    # the JDBC URL; the database is called holidays
    url: jdbc:mysql://localhost:3306/holidays